trigger:
- main  # твоя ветка

pool:
  name: 'Default'  # Windows self-hosted агент

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- powershell: |
    npm install
    npm run build
  displayName: 'npm install and build'

- powershell: |
    # Вход в Azure (предполагается, что сервисное подключение настроено)
    az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
    
    # Деплой React build в статическое веб-приложение
    az staticwebapp upload --name lb-5-front --resource-group lb-5 --source-path ./build
  displayName: 'Deploy to Azure Static Web App'
